version: "3.7"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - version=666
    image: frontend:0.0.3
    container_name: frontend
    ports:
      - 5005:3000
